"""Independent implementation of VS-ePL-KRLS for online regression."""

from .calibration import (
    AdaptiveConformalInterval,
    ConformalState,
    backtest_adaptive_interval,
)
from .decision import (
    DEFAULT_FLEXIBILITY,
    DEFAULT_SIGNAL_THRESHOLD,
    ModelView,
    S10Decision,
    S10DecisionService,
)
from .fuel import (
    FuelEvaluation,
    canonical_product,
    evaluate_fuel_product,
    load_anp_fuel_csv,
    make_lagged_dataset,
)
from .gates import (
    AccuracyReport,
    ChallengerVerdict,
    GateOutcome,
    IntervalReport,
    accuracy_report,
    bootstrap_mean_ci,
    diebold_mariano_hln,
    evaluate_challenger,
    event_mask,
    interval_report,
    moving_block_bootstrap,
    paired_block_bootstrap,
    winkler_score,
)
from .kernels import rbf_features, rbf_kernel, rbf_kernel_matrix
from .krls import KRLSUpdate, SparseKRLS
from .metrics import mae, mse, regression_report, rmse, smape
from .model import VSEPLKRLS, EPLKRLSFixedBeta, VSEPLKRLSConfig
from .monitoring import (
    LedgerAlert,
    LedgerStatus,
    review_ledger,
    review_ledgers,
)
from .news import (
    NEWS_ALL_FEATURES,
    NEWS_CORE_FEATURES,
    NewsFeatureSnapshot,
    augment_supervised_with_news,
    load_weekly_news_features,
)
from .news_annotation import (
    ANNOTATION_COLUMNS,
    AnnotationBatch,
    build_annotation_batch,
    merge_annotation_slots,
    validate_annotations,
)
from .news_annotation_simulation import (
    SimulatedLabel,
    simulate_annotation_slot,
    simulate_label,
)
from .news_pressure import (
    NEWS_PRESSURE_FEATURES,
    NewsCorpusSnapshot,
    NewsPressureConfig,
    NewsPressureFeatures,
    OnlineNewsPressureClassifier,
    WeeklyNewsDocuments,
    augment_supervised_with_pressure,
    build_weekly_news_documents,
    generate_prequential_pressure_features,
    load_news_corpus,
    market_pressure_labels,
)
from .performance import (
    MovementAccuracy,
    PerformanceReport,
    PriceAccuracy,
    Profitability,
    performance_report,
)
from .pressure import (
    PRESSURE_FEATURES,
    PRESSURE_GATE_Z,
    build_pressure_features,
)
from .regional import (
    UF_REGION,
    PooledReversion,
    pool_reversion,
    SpreadConfig,
    SpreadForecast,
    SpreadForecaster,
    build_regional_panel,
    fetch_regional_producer,
    fetch_state_weekly,
)
from .rule import EvolvingRule
from .shadow import (
    S10ResidualHybridShadow,
    S10ShadowForecast,
    S10ShadowHealth,
    append_shadow_ledger,
    verify_shadow_ledger,
)
from .utils import MinMaxScaler, RunningTargetStats

__all__ = [
    "ANNOTATION_COLUMNS",
    "AccuracyReport",
    "AdaptiveConformalInterval",
    "AnnotationBatch",
    "ChallengerVerdict",
    "ConformalState",
    "DEFAULT_FLEXIBILITY",
    "DEFAULT_SIGNAL_THRESHOLD",
    "EPLKRLSFixedBeta",
    "EvolvingRule",
    "FuelEvaluation",
    "GateOutcome",
    "IntervalReport",
    "KRLSUpdate",
    "LedgerAlert",
    "LedgerStatus",
    "MinMaxScaler",
    "ModelView",
    "MovementAccuracy",
    "NEWS_ALL_FEATURES",
    "NEWS_CORE_FEATURES",
    "NEWS_PRESSURE_FEATURES",
    "NewsCorpusSnapshot",
    "NewsFeatureSnapshot",
    "NewsPressureConfig",
    "NewsPressureFeatures",
    "OnlineNewsPressureClassifier",
    "PRESSURE_FEATURES",
    "PRESSURE_GATE_Z",
    "PerformanceReport",
    "PooledReversion",
    "PriceAccuracy",
    "Profitability",
    "RunningTargetStats",
    "S10Decision",
    "S10DecisionService",
    "S10ResidualHybridShadow",
    "S10ShadowForecast",
    "S10ShadowHealth",
    "SimulatedLabel",
    "SparseKRLS",
    "SpreadConfig",
    "SpreadForecast",
    "SpreadForecaster",
    "UF_REGION",
    "VSEPLKRLS",
    "VSEPLKRLSConfig",
    "WeeklyNewsDocuments",
    "accuracy_report",
    "append_shadow_ledger",
    "augment_supervised_with_news",
    "augment_supervised_with_pressure",
    "backtest_adaptive_interval",
    "bootstrap_mean_ci",
    "build_annotation_batch",
    "build_pressure_features",
    "build_regional_panel",
    "build_weekly_news_documents",
    "canonical_product",
    "diebold_mariano_hln",
    "evaluate_challenger",
    "evaluate_fuel_product",
    "event_mask",
    "fetch_regional_producer",
    "fetch_state_weekly",
    "generate_prequential_pressure_features",
    "interval_report",
    "load_anp_fuel_csv",
    "load_news_corpus",
    "load_weekly_news_features",
    "mae",
    "make_lagged_dataset",
    "market_pressure_labels",
    "merge_annotation_slots",
    "moving_block_bootstrap",
    "mse",
    "paired_block_bootstrap",
    "performance_report",
    "pool_reversion",
    "rbf_features",
    "rbf_kernel",
    "rbf_kernel_matrix",
    "regression_report",
    "review_ledger",
    "review_ledgers",
    "rmse",
    "simulate_annotation_slot",
    "simulate_label",
    "smape",
    "validate_annotations",
    "verify_shadow_ledger",
    "winkler_score",
]

__version__ = "0.2.0"
